version: '3.4'

services:
  WorkerServiceNachislenie:
    image: rgrty-worker-service-nachislenie
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: rgrty-worker-service-nachislenie
    restart: 'no'
    