version: '3.4'

services:
  vueapp:
    image: rgrty-vue-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: rgrty-vue-app
    restart: 'no'
    ports:
      - 3000:80
    