version: '3.4'

services:
  payservice:
    image: rgrty-pay-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: rgrty-pay-service
    restart: 'no'    
    ports:
      - 5215:80
    