version: '3.4'

services:
  WorkerServiceNachislenie:
    image: rgrty-worker-service-nachislenie
    build:
      context: ../WorkerService_Nachislenie
      dockerfile: Dockerfile
    container_name: rgrty-worker-service-nachislenie
    restart: 'no'
    env_file:
      - ".env"

  abonentdataaccountingservice:
    image: rgrty-abonent-data-accounting-service
    build:
      context: ../webapi
      dockerfile: Dockerfile
    container_name: rgrty-abonent-data-accounting-service
    restart: 'no'
    env_file:
      - ".env"
    networks:
      - rgrty-billing-docker-net

  vueapp:
    image: rgrty-vue-app
    build:
      context: ../vueapp
      dockerfile: Dockerfile
    container_name: rgrty-vue-app
    restart: 'no'
    depends_on:
      - abonentdataaccountingservice
      - repairrequestsservice
      - payservice
      - nachislservice
      - authservice
    env_file:
      - ".env"
    ports:
      - 3000:80
    networks:
      - rgrty-billing-docker-net
  
  repairrequestsservice:
    image: rgrty-repair-requests-service
    build:
      context: ../RepairRequestsService
      dockerfile: Dockerfile 
    container_name: rgrty-repair-requests-service
    restart: 'no'       
    env_file:
      - ".env"
    networks:
      - rgrty-billing-docker-net
  
  payservice:
    image: rgrty-pay-service
    build:
      context: ../PayService
      dockerfile: Dockerfile
    container_name: rgrty-pay-service
    restart: 'no'       
    env_file:
      - ".env"
    networks:
      - rgrty-billing-docker-net
  
  nachislservice:
    image: rgrty-nachisl-service
    build:
      context: ../NachislService
      dockerfile: Dockerfile
    container_name: rgrty-nachisl-service
    restart: 'no'
    env_file:
      - ".env"
    networks:
      - rgrty-billing-docker-net
  
  authservice:
    image: rgrty-auth-service
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    container_name: rgrty-auth-service
    restart: 'no'
    env_file:
      - ".env"
    environment:
      AbonentDataAccountingService_URL: ${AbonentDataAccountingService_URL}
    networks:
      - rgrty-billing-docker-net
  
networks:
    rgrty-billing-docker-net:
        driver: bridge
    
