version: '3.4'

services:
  WorkerServiceNachislenie:
    image: rgrty-worker-service-nachislenie
    build:
      context: ../WorkerService_Nachislenie
      dockerfile: Dockerfile
    container_name: rgrty-worker-service-nachislenie
    restart: 'no'

  abonentdataaccountingservice:
    image: rgrty-abonent-data-accounting-service
    build:
      context: ../webapi
      dockerfile: Dockerfile
    container_name: rgrty-abonent-data-accounting-service
    restart: 'no'    
    environment:
      AuthService_URL: ${AuthService_URL}
      PayService_URL: ${PayService_URL}
    networks:
      - rgrty-billing-docker-net

  vueapp:
    image: rgrty-vue-app
    build:
      context: ../vueapp
      dockerfile: Dockerfile
    container_name: rgrty-vue-app
    restart: 'no'
    environment:
      AbonentDataAccountingService_URL: ${AbonentDataAccountingService_URL}
      AuthService_URL: ${AuthService_URL}
      PayService_URL: ${PayService_URL}
      NachislService_URL: ${NachislService_URL}
      RepairReqService_URL: ${RepairReqService_URL}
    ports:
      - 3000:80
    networks:
      - rgrty-billing-docker-net
  
  repairrequestsservice:
    image: rgrty-repair-requests-service
    build:
      context: ../RepairRequestsService
      dockerfile: Dockerfile 
    container_name: rgrty-repair-requests-service
    restart: 'no'       
    environment:
      AuthService_URL: ${AuthService_URL} 
    networks:
      - rgrty-billing-docker-net
  
  payservice:
    image: rgrty-pay-service
    build:
      context: ../PayService
      dockerfile: Dockerfile
    container_name: rgrty-pay-service
    restart: 'no'       
    environment:
      AuthService_URL: ${AuthService_URL}
    networks:
      - rgrty-billing-docker-net
  
  nachislservice:
    image: rgrty-nachisl-service
    build:
      context: ../NachislService
      dockerfile: Dockerfile
    container_name: rgrty-nachisl-service
    restart: 'no'
    environment:
      AuthService_URL: ${AuthService_URL}
      PayService_URL: ${PayService_URL}   
    networks:
      - rgrty-billing-docker-net
  
  authservice:
    image: rgrty-auth-service
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    container_name: rgrty-auth-service
    restart: 'no'    
    environment:
      AbonentDataAccountingService_URL: ${AbonentDataAccountingService_URL}
    networks:
      - rgrty-billing-docker-net

networks:
    rgrty-billing-docker-net:
        driver: bridge
    
