version: '3.4'

services:
  nachislservice:
    image: nachisl-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: nachisl-service
    restart: 'no'    
    ports:
      - 5100:80
    