version: '3.4'

services:
  repairrequestsservice:
    image: rgrty-repair-requests-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: rgrty-repair-requests-service
    restart: 'no'    
    ports:
      - 5278:80
    