version: '3.4'

services:
  authservice:
    image: rgrty-auth-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: rgrty-auth-service
    restart: 'always'    
    ports:
      - 5089:80
    